import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google"; 
import "./globals.css";
import Navbar from "../components/sections/Navbar";
import Footer from "../components/sections/Footer";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "HanZWorld | Music Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="luxury">
      <body
        className={`${oswald.variable} ${inter.variable} antialiased font-sans`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}